In [3]:
# The City College of New York, City University of New York
# Written by Hasan Suca Kayman and Prof. M. Umit Uyar
# September, 2025
# Algorithmic trading of financial stocks using ANNs

In [4]:
import numpy as np
import pandas as pd
import time
from tensorflow import keras

keras.utils.set_random_seed(42)

#this is a utility function to be called later in the code:
def print_weights(weights):
    # weights = model.get_weights();
    print('\n******* WEIGHTS OF ANN *******\n')
    for i in range(int(len(weights)/2)):
        print('Weights W%d:\n' %(i), weights[i*2])
        print('Bias b%d:\n' %(i), weights[(i*2)+1])

#% DATA EXTRACTION
historical_data_file = 'MSFT.csv'
print('\n********* NOW READING SAMLE DATA USING ', historical_data_file,'*********')
time.sleep(3)

## load the historical stock data
df = pd.read_csv(historical_data_file) # (df stands for data frame)
df

********* NOW READING SAMLE DATA USING  MSFT.csv *********

,Date,Open,High,Low,Close,Adj Close,Volume
0,3/20/2019,117.389999,118.750000,116.709999,117.519997,115.985443,28113300
1,3/21/2019,117.139999,120.820000,117.089996,120.220001,118.650192,29854400
2,3/22/2019,119.500000,119.589996,117.040001,117.050003,115.521576,33624500
3,3/25/2019,116.559998,118.010002,116.320000,117.660004,116.123627,27067100
4,3/26/2019,118.620003,118.709999,116.849998,117.910004,116.370346,26097700
...,...,...,...,...,...,...,...
249,3/16/2020,140.000000,149.350006,135.000000,135.419998,135.419998,87905900
250,3/17/2020,140.000000,147.500000,135.000000,146.570007,146.570007,81059800
251,3/18/2020,138.000000,146.000000,135.020004,140.399994,140.399994,81593200
252,3/19/2020,142.770004,150.149994,139.000000,142.710007,142.710007,85801400
253,3/20/2020,146.000000,147.070007,143.130005,144.929993,144.929993,32760246

In [5]:
# define technical indicators for alogirhtmic trading:
short_window = 10
long_window = 30
momentum_window = 40

## calculate the Simple Moving Average and add it to a new column in df;
## rolling means moving window starting from the current entry and
## the last 5 days
df['SMA'] = df['Close'].rolling(short_window).mean()
df

,Date,Open,High,Low,Close,Adj Close,Volume,SMA
0,3/20/2019,117.389999,118.750000,116.709999,117.519997,115.985443,28113300,NaN
1,3/21/2019,117.139999,120.820000,117.089996,120.220001,118.650192,29854400,NaN
2,3/22/2019,119.500000,119.589996,117.040001,117.050003,115.521576,33624500,NaN
3,3/25/2019,116.559998,118.010002,116.320000,117.660004,116.123627,27067100,NaN
4,3/26/2019,118.620003,118.709999,116.849998,117.910004,116.370346,26097700,NaN
...,...,...,...,...,...,...,...,...
249,3/16/2020,140.000000,149.350006,135.000000,135.419998,135.419998,87905900,156.138001
250,3/17/2020,140.000000,147.500000,135.000000,146.570007,146.570007,81059800,154.344002
251,3/18/2020,138.000000,146.000000,135.020004,140.399994,140.399994,81593200,151.329001
252,3/19/2020,142.770004,150.149994,139.000000,142.710007,142.710007,85801400,148.973001
253,3/20/2020,146.000000,147.070007,143.130005,144.929993,144.929993,32760246,147.309000

In [6]:
## calculate the Exponential Moving Average and add it
## to a new column in df;
## ewm means exponential moving average
df['EMA'] = df['Close'].ewm(span=long_window).mean()
df

,Date,Open,High,Low,Close,Adj Close,Volume,SMA,EMA
0,3/20/2019,117.389999,118.750000,116.709999,117.519997,115.985443,28113300,NaN,117.519997
1,3/21/2019,117.139999,120.820000,117.089996,120.220001,118.650192,29854400,NaN,118.914999
2,3/22/2019,119.500000,119.589996,117.040001,117.050003,115.521576,33624500,NaN,118.251444
3,3/25/2019,116.559998,118.010002,116.320000,117.660004,116.123627,27067100,NaN,118.088481
4,3/26/2019,118.620003,118.709999,116.849998,117.910004,116.370346,26097700,NaN,118.047873
...,...,...,...,...,...,...,...,...,...
249,3/16/2020,140.000000,149.350006,135.000000,135.419998,135.419998,87905900,156.138001,163.742999
250,3/17/2020,140.000000,147.500000,135.000000,146.570007,146.570007,81059800,154.344002,162.635064
251,3/18/2020,138.000000,146.000000,135.020004,140.399994,140.399994,81593200,151.329001,161.200543
252,3/19/2020,142.770004,150.149994,139.000000,142.710007,142.710007,85801400,148.973001,160.007605
253,3/20/2020,146.000000,147.070007,143.130005,144.929993,144.929993,32760246,147.309000,159.034856

In [7]:
## calculate the Momentum and add it to a new column in df;
## Momentum is defined as close [today] / close [5 days ago]
df['Momentum'] = df['Close'] / df['Close'].shift(momentum_window)
df

,Date,Open,High,Low,Close,Adj Close,Volume,SMA,EMA,Momentum
0,3/20/2019,117.389999,118.750000,116.709999,117.519997,115.985443,28113300,NaN,117.519997,NaN
1,3/21/2019,117.139999,120.820000,117.089996,120.220001,118.650192,29854400,NaN,118.914999,NaN
2,3/22/2019,119.500000,119.589996,117.040001,117.050003,115.521576,33624500,NaN,118.251444,NaN
3,3/25/2019,116.559998,118.010002,116.320000,117.660004,116.123627,27067100,NaN,118.088481,NaN
4,3/26/2019,118.620003,118.709999,116.849998,117.910004,116.370346,26097700,NaN,118.047873,NaN
...,...,...,...,...,...,...,...,...,...,...
249,3/16/2020,140.000000,149.350006,135.000000,135.419998,135.419998,87905900,156.138001,163.742999,0.814949
250,3/17/2020,140.000000,147.500000,135.000000,146.570007,146.570007,81059800,154.344002,162.635064,0.877139
251,3/18/2020,138.000000,146.000000,135.020004,140.399994,140.399994,81593200,151.329001,161.200543,0.843243
252,3/19/2020,142.770004,150.149994,139.000000,142.710007,142.710007,85801400,148.973001,160.007605,0.861255
253,3/20/2020,146.000000,147.070007,143.130005,144.929993,144.929993,32760246,147.309000,159.034856,0.869302

In [8]:
## calculate the standard deviation of SMA over a rolling window
## ddof means degree of freedom, set it to zero to get the population std
df['STD'] = df['Close'].rolling(short_window).std(ddof=0)
## calculate the Bollinger Band for each day
## BB > 1 means the closing price is above the upper band
## BB < -1 means the closing price is below the lower band
df['BB'] = (df['Close'] - df['SMA']) / (2 * df['STD'])
df

,Date,Open,High,Low,Close,Adj Close,Volume,SMA,EMA,Momentum,STD,BB
0,3/20/2019,117.389999,118.750000,116.709999,117.519997,115.985443,28113300,NaN,117.519997,NaN,NaN,NaN
1,3/21/2019,117.139999,120.820000,117.089996,120.220001,118.650192,29854400,NaN,118.914999,NaN,NaN,NaN
2,3/22/2019,119.500000,119.589996,117.040001,117.050003,115.521576,33624500,NaN,118.251444,NaN,NaN,NaN
3,3/25/2019,116.559998,118.010002,116.320000,117.660004,116.123627,27067100,NaN,118.088481,NaN,NaN,NaN
4,3/26/2019,118.620003,118.709999,116.849998,117.910004,116.370346,26097700,NaN,118.047873,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
249,3/16/2020,140.000000,149.350006,135.000000,135.419998,135.419998,87905900,156.138001,163.742999,0.814949,10.943980,-0.946548
250,3/17/2020,140.000000,147.500000,135.000000,146.570007,146.570007,81059800,154.344002,162.635064,0.877139,10.894856,-0.356774
251,3/18/2020,138.000000,146.000000,135.020004,140.399994,140.399994,81593200,151.329001,161.200543,0.843243,10.138429,-0.538989
252,3/19/2020,142.770004,150.149994,139.000000,142.710007,142.710007,85801400,148.973001,160.007605,0.861255,9.074268,-0.345096
253,3/20/2020,146.000000,147.070007,143.130005,144.929993,144.929993,32760246,147.309000,159.034856,0.869302,8.083290,-0.147156

In [9]:
## define the output for the ANN:
## calculate the percent change of closing price for each day
## shift(-1) means yesterday (applies to each element of df)
increase = df['Close'] - df['Close'].shift(-1)
df['Percent_Change'] = (increase / df['Close'].shift(-1))*100
df

,Date,Open,High,Low,Close,Adj Close,Volume,SMA,EMA,Momentum,STD,BB,Percent_Change
0,3/20/2019,117.389999,118.750000,116.709999,117.519997,115.985443,28113300,NaN,117.519997,NaN,NaN,NaN,-2.245886
1,3/21/2019,117.139999,120.820000,117.089996,120.220001,118.650192,29854400,NaN,118.914999,NaN,NaN,NaN,2.708243
2,3/22/2019,119.500000,119.589996,117.040001,117.050003,115.521576,33624500,NaN,118.251444,NaN,NaN,NaN,-0.518444
3,3/25/2019,116.559998,118.010002,116.320000,117.660004,116.123627,27067100,NaN,118.088481,NaN,NaN,NaN,-0.212026
4,3/26/2019,118.620003,118.709999,116.849998,117.910004,116.370346,26097700,NaN,118.047873,NaN,NaN,NaN,0.976284
...,...,...,...,...,...,...,...,...,...,...,...,...,...
249,3/16/2020,140.000000,149.350006,135.000000,135.419998,135.419998,87905900,156.138001,163.742999,0.814949,10.943980,-0.946548,-7.607292
250,3/17/2020,140.000000,147.500000,135.000000,146.570007,146.570007,81059800,154.344002,162.635064,0.877139,10.894856,-0.356774,4.394596
251,3/18/2020,138.000000,146.000000,135.020004,140.399994,140.399994,81593200,151.329001,161.200543,0.843243,10.138429,-0.538989,-1.618676
252,3/19/2020,142.770004,150.149994,139.000000,142.710007,142.710007,85801400,148.973001,160.007605,0.861255,9.074268,-0.345096,-1.531764
253,3/20/2020,146.000000,147.070007,143.130005,144.929993,144.929993,32760246,147.309000,159.034856,0.869302,8.083290,-0.147156,NaN

In [10]:
# remove remove rows that contain non-numerical values:
df = df.dropna(axis=0)
df

,Date,Open,High,Low,Close,Adj Close,Volume,SMA,EMA,Momentum,STD,BB,Percent_Change
40,5/16/2019,126.750000,129.380005,126.459999,128.929993,127.717468,30112200,126.373998,125.202778,1.097090,1.756467,0.727596,0.671497
41,5/17/2019,128.309998,130.460007,127.919998,128.070007,126.865570,25770500,126.290999,125.399724,1.065297,1.651625,0.538563,1.465700
42,5/20/2019,126.519997,127.589996,125.760002,126.220001,125.032967,23706900,126.097999,125.455834,1.078343,1.531514,0.039830,-0.535856
43,5/21/2019,127.430000,127.529999,126.580002,126.900002,125.706573,15293300,126.236000,125.554237,1.078531,1.535384,0.216233,-0.603114
44,5/22/2019,126.620003,128.240005,126.519997,127.669998,126.469322,15396500,126.452000,125.697882,1.082775,1.569610,0.387994,1.180851
...,...,...,...,...,...,...,...,...,...,...,...,...,...
248,3/13/2020,147.500000,161.910004,140.729996,158.830002,158.830002,92727400,159.875000,165.696309,0.973342,9.518973,-0.054890,17.286962
249,3/16/2020,140.000000,149.350006,135.000000,135.419998,135.419998,87905900,156.138001,163.742999,0.814949,10.943980,-0.946548,-7.607292
250,3/17/2020,140.000000,147.500000,135.000000,146.570007,146.570007,81059800,154.344002,162.635064,0.877139,10.894856,-0.356774,4.394596
251,3/18/2020,138.000000,146.000000,135.020004,140.399994,140.399994,81593200,151.329001,161.200543,0.843243,10.138429,-0.538989,-1.618676
252,3/19/2020,142.770004,150.149994,139.000000,142.710007,142.710007,85801400,148.973001,160.007605,0.861255,9.074268,-0.345096,-1.531764

In [11]:
# define the inputs of the ANN:
X = np.array(df[['SMA','EMA','Momentum','BB']])
# define the output of the ANN:
Y = np.array(df['Percent_Change'])

In [12]:
# print the first 10 rows of X
X[:10]

array([[ 1.26373998e+02,  1.25202778e+02,  1.09708983e+00,
         7.27595759e-01],
       [ 1.26290999e+02,  1.25399724e+02,  1.06529700e+00,
         5.38562944e-01],
       [ 1.26097999e+02,  1.25455834e+02,  1.07834257e+00,
         3.98303616e-02],
       [ 1.26236000e+02,  1.25554237e+02,  1.07853134e+00,
         2.16233268e-01],
       [ 1.26452000e+02,  1.25697882e+02,  1.08277494e+00,
         3.87994043e-01],
       [ 1.26520000e+02,  1.25730504e+02,  1.08058579e+00,
        -1.10291432e-01],
       [ 1.26431000e+02,  1.25764870e+02,  1.07962027e+00,
        -6.24505046e-02],
       [ 1.26712000e+02,  1.25791444e+02,  1.06969647e+00,
        -2.40439371e-01],
       [ 1.26733000e+02,  1.25734338e+02,  1.04973958e+00,
        -8.05606752e-01],
       [ 1.26704001e+02,  1.25734048e+02,  1.05487038e+00,
        -4.29227908e-01]])

In [13]:
# print the first 10 rows of Y
Y[:10]

array([ 0.6714968 ,  1.46569956, -0.53585578, -0.60311429,  1.18085117,
       -0.04752693,  0.06340678,  0.97647029, -0.62833133,  1.65750566])

In [14]:
## create a model for the ANN
model = keras.Sequential()
# Create ANN with 4 inputs + 2 hidden layers + 1 output layer
## first hidden layer that accepts 4 input features (SMA, EMA, Momentum, BB);
## Dense means every neuron in the layer connects to every neuron in the
## previous layer.
## define input layer:
model.add(keras.layers.Input(shape=(4,)))
## add the first hidden layer with 4 neurons to the ANN:
model.add(keras.layers.Dense(24, activation='relu'))
## add the second hidden layer with 3 neurons to the ANN:
model.add(keras.layers.Dense(12, activation='relu'))
model.add(keras.layers.Dense(6, activation='relu'))
## add an output layer with a single output (Percentage_Change):
model.add(keras.layers.Dense(1, activation='linear'))

## set the optimization algorithm used for minimizing loss function
## use gradient descent (adam) to minimize error (loss)
model.compile(optimizer='adam', loss='mean_squared_error')
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 24)             │           120 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 12)             │           300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 6)              │            78 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │             7 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 505 (1.97 KB)

 Trainable params: 505 (1.97 KB)

 Non-trainable params: 0 (0.00 B)

In [15]:
# print the initial values of weights:
weights = model.get_weights()
print_weights(weights)

******* WEIGHTS OF ANN *******

Weights W0:
 [[ 0.33161867  0.15056479 -0.13080841  0.4166094  -0.3906395   0.14103234
   0.43559825 -0.30745363  0.0220246   0.12105983 -0.38290226 -0.04966331
   0.43146336 -0.02745882  0.00272781  0.24595892 -0.44547692 -0.28479993
   0.01318514 -0.4014127  -0.42805758  0.3221544   0.38461155 -0.21984449]
 [ 0.33286184 -0.34489155 -0.03491694  0.05806917  0.06174469 -0.277596
  -0.2687723   0.45287776 -0.36116892 -0.05220395 -0.21748574 -0.35086614
   0.21584845 -0.29409546  0.16784728  0.13926095 -0.42344162  0.05891532
  -0.15357345 -0.10475951  0.4208051  -0.08295897  0.02913573 -0.22652993]
 [-0.34920347  0.19981974  0.10777813  0.00736541 -0.4372075  -0.35210896
   0.26977664  0.33901608 -0.06309479 -0.17242557 -0.4323039  -0.42708758
   0.23984641  0.30424023 -0.11481899  0.2032708  -0.17026648  0.25822902
  -0.17101553 -0.07086194  0.32846332  0.30310297  0.17268485  0.367451  ]
 [ 0.32662755 -0.25405276  0.12542218 -0.37972218  0.42043322  0.20266896
   0.05608809 -0.28907079 -0.2794646   0.43758482 -0.41598526 -0.17083928
  -0.24328046 -0.3176739   0.33648884  0.31282264  0.1162852   0.03345171
   0.04189628  0.19843584 -0.01703548 -0.34165573  0.37003833 -0.12108901]]
Bias b0:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Weights W1:
 [[ 0.39122915 -0.01468235  0.21726805  0.19830477  0.25801235 -0.31134745
   0.16586763  0.02400401 -0.34962454 -0.1554113  -0.22551437  0.01421914]
 [ 0.09338731  0.11419362 -0.0018293  -0.3769464   0.19225776  0.2750998
  -0.31584692  0.05204263  0.22899592  0.3797133   0.04315186  0.3651724 ]
 [ 0.1397357   0.2948516  -0.02824515 -0.23608913  0.10186052  0.02745053
  -0.20646055  0.03833529  0.3340068   0.24239838 -0.2853408  -0.36026374]
 [-0.32875565 -0.2728536  -0.3218713  -0.12408984 -0.18661785  0.360444
   0.00482038  0.24767429  0.14745468  0.39367974 -0.3828408  -0.20766205]
 [-0.2384991  -0.19820002  0.20615512  0.22295058  0.38887805  0.04148996
   0.28542423  0.22163665  0.04801807  0.4074012   0.07498571 -0.15822348]
 [ 0.23354751 -0.21204071 -0.3092175  -0.06056723  0.06553653  0.12718707
   0.03600949 -0.17167446  0.25929528 -0.20887181  0.38696223  0.08377448]
 [-0.32194138 -0.04916233  0.18225902  0.36690587  0.3395173  -0.26389578
  -0.00775129 -0.39330345  0.15639973 -0.03610322  0.2818818   0.30737936]
 [ 0.25606215 -0.14743313 -0.22074412  0.16312063  0.01272291 -0.2477507
  -0.30201498  0.28267813 -0.3439268   0.3063367  -0.06898314 -0.36198148]
 [ 0.13200319 -0.14528781  0.12459916  0.22038168  0.13433737 -0.1838781
   0.08676732 -0.05202395  0.39707106 -0.16896498 -0.37439817 -0.18528798]
 [-0.01082462 -0.34423524 -0.38199976 -0.15814805 -0.00135061  0.3891067
  -0.40393135  0.24697274 -0.22242168  0.16117465  0.03048345 -0.23634101]
 [ 0.19557941 -0.23011613 -0.06930462 -0.20218769  0.40559024 -0.37780565
   0.03690952  0.1079607  -0.25146943 -0.15476367 -0.10156274 -0.00215742]
 [-0.13248128  0.21352106  0.04750308 -0.04521143 -0.2433118  -0.28821838
  -0.2952232  -0.10035601  0.0813826   0.35663432 -0.1718963  -0.05378723]
 [-0.27001286 -0.15378982 -0.18482302 -0.37621802  0.18715298  0.2635265
   0.17253983 -0.34040827 -0.02684587  0.30892318  0.285078   -0.2676453 ]
 [ 0.30695546 -0.13160986  0.24969429  0.09783328 -0.39420602 -0.17127793
  -0.09240121  0.08734518  0.3176362   0.28479463 -0.21949182  0.25361282]
 [ 0.26872444  0.24788034  0.09355539  0.10970122  0.27348417 -0.37135473
   0.13215315 -0.00050312 -0.08641407  0.36178088  0.15950227 -0.21687889]
 [ 0.00201043 -0.20133223  0.18489885  0.08168763  0.09135708 -0.11235368
  -0.16600427  0.32980716 -0.21822755  0.26230252 -0.22805537  0.20321369]
 [-0.28990924  0.12328303 -0.24208635  0.3065698   0.22652721  0.0900718
  -0.37237245  0.28731704  0.07723364  0.00971696  0.04243782  0.04658774]
 [ 0.09720325 -0.18364294 -0.20064212 -0.31361115  0.01557013 -0.06981066
  -0.31695807 -0.18793906  0.12414402  0.3094588  -0.25228083 -0.3910747 ]
 [-0.36863405 -0.24501455  0.03063646 -0.39763677  0.16436768 -0.08467257
   0.03562239  0.12213808 -0.37292492 -0.25202814 -0.27751094  0.04298958]
 [-0.27184242  0.11750215 -0.10061395  0.09235126  0.2079863   0.22689098
  -0.18926884  0.19524294 -0.0237416   0.11254376 -0.04797903 -0.31686562]
 [ 0.27997476  0.03758872  0.06452659  0.38551068 -0.38782424 -0.06557566
   0.32653552 -0.3109738  -0.3092794  -0.307581   -0.15347037 -0.02346548]
 [ 0.38613868 -0.29298395  0.31179655  0.12296915  0.39496613 -0.29892987
   0.02882409 -0.07162282 -0.35767308  0.1810047  -0.14963251  0.24285978]
 [-0.15465853  0.3216378  -0.22584948 -0.18430044  0.3247187  -0.10635266
  -0.11235777  0.28316462 -0.40781012  0.03368554  0.3889103   0.37004328]
 [-0.17548548  0.1350025  -0.13515699  0.00182024  0.02983609 -0.31179413
  -0.05736914  0.05750871  0.30046016  0.37416095 -0.08465311 -0.16969147]]
Bias b1:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Weights W2:
 [[ 0.39588767 -0.0266645  -0.1359407  -0.3622032  -0.12195399  0.41513264]
 [-0.46619993 -0.07189471 -0.49667257 -0.44872046 -0.1863108   0.16195911]
 [-0.19352221  0.56862116  0.08800417 -0.23918629 -0.04357934  0.07230037]
 [-0.14780211 -0.02696157 -0.072227    0.52361643 -0.40375566 -0.30968535]
 [-0.4347855   0.3596034   0.28047884  0.07645965  0.41763306 -0.3449151 ]
 [ 0.32321483  0.29233235 -0.5416177   0.11958379  0.5720519   0.34029138]
 [ 0.23533702  0.13673317 -0.23817042 -0.3112093   0.09442848  0.5361966 ]
 [-0.4049692  -0.43897492  0.19052827 -0.06338227 -0.00112444  0.31073374]
 [ 0.28477174  0.4983487  -0.5532949  -0.13749796 -0.23661855  0.12285906]
 [-0.1846002  -0.47541004  0.26044112 -0.51706517  0.31294     0.05077851]
 [ 0.4669323  -0.04808551 -0.06781501 -0.27811772 -0.39715308 -0.44178134]
 [-0.44397578  0.09682953  0.47793305 -0.00960845  0.31214118 -0.3704466 ]]
Bias b2:
 [0. 0. 0. 0. 0. 0.]
Weights W3:
 [[0.5850214 ]
 [0.25263417]
 [0.00216144]
 [0.339288  ]
 [0.66559327]
 [0.35184705]]
Bias b3:
 [0.]

In [16]:
## train the ANN model using 200 iterations
model.fit(X, Y, epochs=50, verbose=0)

print('\n\n********** ANN training complete **********\n\n')

********** ANN training complete **********

In [17]:
# print the weighst after training:
weights = model.get_weights();
print_weights(weights)

******* WEIGHTS OF ANN *******

Weights W0:
 [[ 0.33955526  0.15056479 -0.13080841  0.33049354 -0.3906395   0.14103234
   0.37618345 -0.3504362   0.0220246   0.12373874 -0.38290226 -0.04966331
   0.3675815  -0.02745882 -0.05425623  0.18552463 -0.44547692 -0.28479993
   0.01318514 -0.4014127  -0.34113544  0.2711191   0.32579964 -0.21984449]
 [ 0.34053499 -0.34489155 -0.03491694 -0.02799635  0.06174469 -0.277596
  -0.3279576   0.4097231  -0.36116892 -0.04928238 -0.21748574 -0.35086614
   0.15205711 -0.29409546  0.11081079  0.07879236 -0.42344162  0.05891532
  -0.15357345 -0.10475951  0.5074756  -0.13403325 -0.02959741 -0.22652993]
 [-0.34127766  0.19981974  0.10777813 -0.07890062 -0.4372075  -0.35210896
   0.21053633  0.29490215 -0.06309479 -0.17420158 -0.4323039  -0.42708758
   0.17620611  0.30424023 -0.17167339  0.14247452 -0.17026648  0.25822902
  -0.17101553 -0.07086194  0.41524413  0.25212112  0.1137652   0.367451  ]
 [ 0.34564206 -0.25405276  0.12542218 -0.45698744  0.42043322  0.20266896
  -0.00907733 -0.3560758  -0.2794646   0.32837203 -0.41598526 -0.17083928
  -0.30149868 -0.3176739   0.28742063  0.2449374   0.1162852   0.03345171
   0.04189628  0.19843584  0.05890922 -0.38988173  0.30454665 -0.12108901]]
Bias b0:
 [ 0.00721023  0.          0.         -0.08639656  0.          0.
 -0.05853327 -0.04404368  0.          0.00126114  0.          0.
 -0.06349906  0.         -0.05706931 -0.06072385  0.          0.
  0.          0.          0.08608175 -0.05105513 -0.05856058  0.        ]
Weights W1:
 [[ 0.46954253 -0.01468235  0.21726805  0.19830477  0.19823955 -0.31134745
   0.11273967  0.05816578 -0.34962454 -0.22543511 -0.22551437  0.01421914]
 [ 0.09338731  0.11419362 -0.0018293  -0.3769464   0.19225776  0.2750998
  -0.31584692  0.05204263  0.22899592  0.3797133   0.04315186  0.3651724 ]
 [ 0.1397357   0.2948516  -0.02824515 -0.23608913  0.10186052  0.02745053
  -0.20646055  0.03833529  0.3340068   0.24239838 -0.2853408  -0.36026374]
 [-0.25801006 -0.2728536  -0.3218713  -0.12408984 -0.24221472  0.360444
  -0.04559847  0.28183052  0.14745468  0.3297443  -0.3828408  -0.20766205]
 [-0.2384991  -0.19820002  0.20615512  0.22295058  0.38887805  0.04148996
   0.28542423  0.22163665  0.04801807  0.4074012   0.07498571 -0.15822348]
 [ 0.23354751 -0.21204071 -0.3092175  -0.06056723  0.06553653  0.12718707
   0.03600949 -0.17167446  0.25929528 -0.20887181  0.38696223  0.08377448]
 [-0.25897977 -0.04916233  0.18225902  0.36690587  0.29126036 -0.26389578
  -0.0514034  -0.35557508  0.15639973 -0.08983643  0.2818818   0.30737936]
 [ 0.3183567  -0.14743313 -0.22074412  0.16312063 -0.0365136  -0.2477507
  -0.34910318  0.3125053  -0.3439268   0.2506116  -0.06898314 -0.36198148]
 [ 0.13200319 -0.14528781  0.12459916  0.22038168  0.13433737 -0.1838781
   0.08676732 -0.05202395  0.39707106 -0.16896498 -0.37439817 -0.18528798]
 [ 0.07854769 -0.34423524 -0.38199976 -0.15814805 -0.06353702  0.3891067
  -0.45610678  0.28027377 -0.22242168  0.08748952  0.03048345 -0.23634101]
 [ 0.19557941 -0.23011613 -0.06930462 -0.20218769  0.40559024 -0.37780565
   0.03690952  0.1079607  -0.25146943 -0.15476367 -0.10156274 -0.00215742]
 [-0.13248128  0.21352106  0.04750308 -0.04521143 -0.2433118  -0.28821838
  -0.2952232  -0.10035601  0.0813826   0.35663432 -0.1718963  -0.05378723]
 [-0.19591855 -0.15378982 -0.18482302 -0.37621802  0.12957758  0.2635265
   0.12075117 -0.30630112 -0.02684587  0.24211973  0.285078   -0.2676453 ]
 [ 0.30695546 -0.13160986  0.24969429  0.09783328 -0.39420602 -0.17127793
  -0.09240121  0.08734518  0.3176362   0.28479463 -0.21949182  0.25361282]
 [ 0.33014703  0.24788034  0.09355539  0.10970122  0.22507843 -0.37135473
   0.08720657  0.03329354 -0.08641407  0.30764526  0.15950227 -0.21687889]
 [ 0.07363284 -0.20133223  0.18489885  0.08168763  0.03567453 -0.11235368
  -0.21624666  0.36396182 -0.21822755  0.19812779 -0.22805537  0.20321369]
 [-0.28990924  0.12328303 -0.24208635  0.3065698   0.22652721  0.0900718
  -0.37237245  0.28731704  0.07723364  0.00971696  0.04243782  0.04658774]
 [ 0.09720325 -0.18364294 -0.20064212 -0.31361115  0.01557013 -0.06981066
  -0.31695807 -0.18793906  0.12414402  0.3094588  -0.25228083 -0.3910747 ]
 [-0.36863405 -0.24501455  0.03063646 -0.39763677  0.16436768 -0.08467257
   0.03562239  0.12213808 -0.37292492 -0.25202814 -0.27751094  0.04298958]
 [-0.27184242  0.11750215 -0.10061395  0.09235126  0.2079863   0.22689098
  -0.18926884  0.19524294 -0.0237416   0.11254376 -0.04797903 -0.31686562]
 [ 0.4149686   0.03758872  0.06452659  0.38551068 -0.5106677  -0.06557566
   0.23316813 -0.28854388 -0.3092794  -0.44856316 -0.15347037 -0.02346548]
 [ 0.4555278  -0.29298395  0.31179655  0.12296915  0.34177175 -0.29892987
  -0.01939466 -0.0364799  -0.35767308  0.12022132 -0.14963251  0.24285978]
 [-0.08223832  0.3216378  -0.22584948 -0.18430044  0.26869833 -0.10635266
  -0.16268271  0.3177455  -0.40781012 -0.03096568  0.3889103   0.37004328]
 [-0.17548548  0.1350025  -0.13515699  0.00182024  0.02983609 -0.31179413
  -0.05736914  0.05750871  0.30046016  0.37416095 -0.08465311 -0.16969147]]
Bias b1:
 [ 0.07606461  0.          0.          0.         -0.06023392  0.
 -0.0543216   0.03090799  0.         -0.07088088  0.          0.        ]
Weights W2:
 [[ 0.39588767 -0.0266645   0.03591073 -0.3622032  -0.2713619   0.28941357]
 [-0.46619993 -0.07189471 -0.49667257 -0.44872046 -0.1863108   0.16195911]
 [-0.19352221  0.56862116  0.08800417 -0.23918629 -0.04357934  0.07230037]
 [-0.14780211 -0.02696157 -0.072227    0.52361643 -0.40375566 -0.30968535]
 [-0.4347855   0.3596034   0.38595223  0.07645965  0.3586407  -0.432689  ]
 [ 0.32321483  0.29233235 -0.5416177   0.11958379  0.5720519   0.34029138]
 [ 0.23533702  0.13673317 -0.20439573 -0.3112093   0.0631706   0.5083436 ]
 [-0.4049692  -0.43897492  0.30594575 -0.06338227 -0.08086325  0.22752722]
 [ 0.28477174  0.4983487  -0.5532949  -0.13749796 -0.23661855  0.12285906]
 [-0.1846002  -0.47541004  0.35549435 -0.51706517  0.25765312 -0.02649141]
 [ 0.4669323  -0.04808551 -0.06781501 -0.27811772 -0.39715308 -0.44178134]
 [-0.44397578  0.09682953  0.47793305 -0.00960845  0.31214118 -0.3704466 ]]
Bias b2:
 [ 0.          0.          0.12813435  0.         -0.0777719  -0.10135356]
Weights W3:
 [[ 0.5850214 ]
 [ 0.25263417]
 [-0.06444306]
 [ 0.339288  ]
 [ 0.61529684]
 [ 0.24811308]]
Bias b3:
 [-0.0789674]

In [18]:
#% ANN PREDICTION

## insert the inputs for the latest trading day into an array
latest_SMA = df.iloc[-1]['SMA']
latest_EMA = df.iloc[-1]['EMA']
latest_Momentum = df.iloc[-1]['Momentum']
latest_BB = df.iloc[-1]['BB']
latest_inputs = np.array([[latest_SMA, latest_EMA,latest_Momentum,latest_BB]])

prediction = model.predict(latest_inputs)[0,0]
latest_percent_change = df.iloc[-1]['Percent_Change']
print("\ntarget value for percent change: ",latest_percent_change)
print('\n***************************************')
print('ANN Predicted Next Day Stock Movement: %+.2f%%' % (prediction))
print('***************************************')

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step

target value for percent change:  -1.5317643739898654

***************************************
ANN Predicted Next Day Stock Movement: +0.48%
***************************************

In [ ]:
## ask user if they would like to save the ANN model
choice = ''
while choice not in ['y','n']:
    choice = input('\n\nWould you like to save the ANN model? (y/n): \n')
    if choice == 'y':
        save_name = input('\n\nEnter a name for the save file: \n')
        ## if file name does not end with '.h5', add '.h5' to the file name
        if save_name[-3:] != '.h5':
            save_name += '.h5'
        model.save(save_name)
        print('\n\n')
        print('***** ANN MODEL SUCCESSFULLY SAVED AS '+save_name+' *****')
    elif choice == 'n':
        pass
    else:
        print("Invalid input: Input must be 'y' or 'n'")